--
-- 0000 — adoption baseline.
--
-- Meridian ran ad-hoc `CREATE TABLE IF NOT EXISTS` DDL at boot before it had
-- versioned migrations, so this first migration has to land on two kinds of
-- database: a brand-new one, and a deployment whose tables already exist. It is
-- therefore written idempotently, and every object name matches the name the
-- older DDL produced, so adopting a live database is a no-op.
--
-- This is the ONLY migration written this way. Everything from 0001 on is
-- generated by `pnpm db:generate` and applied exactly once.
--

CREATE TABLE IF NOT EXISTS "agent_keys" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"key_hash" text NOT NULL,
	"role" text DEFAULT 'agent' NOT NULL,
	"permissions" jsonb,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"entity_name" text NOT NULL,
	"record_id" uuid NOT NULL,
	"action" text NOT NULL,
	"actor_id" text NOT NULL,
	"actor_type" text NOT NULL,
	"diff" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "migration_jobs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"source" text NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"config" jsonb NOT NULL,
	"report" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plugins" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"name" text NOT NULL,
	"version" text NOT NULL,
	"state" text DEFAULT 'installed' NOT NULL,
	"manifest" jsonb NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "plugins_tenant_id_name_key" UNIQUE("tenant_id","name")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "tenants" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "tenants_slug_key" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"email" text NOT NULL,
	"name" text NOT NULL,
	"role" text DEFAULT 'admin' NOT NULL,
	"password_hash" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_tenant_id_email_key" UNIQUE("tenant_id","email")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "activity" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"type" text,
	"subject" text,
	"notes" text,
	"related_entity" text,
	"related_id" text,
	"due_date" timestamp with time zone,
	"completed" boolean,
	"assigned_to" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "automation" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"entity" text,
	"event" text,
	"conditions" jsonb,
	"actions" jsonb,
	"enabled" boolean
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "comment" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"related_entity" text,
	"related_id" text,
	"body" text,
	"author_name" text,
	"author_id" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "company" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"name" text,
	"industry" text,
	"size" text,
	"website" text,
	"email" text,
	"phone" text,
	"address" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "contact" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"first_name" text,
	"last_name" text,
	"email" text,
	"phone" text,
	"title" text,
	"company_id" text,
	"tags" jsonb,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "deal" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"title" text,
	"value" numeric(15, 2),
	"stage" text,
	"probability" integer,
	"contact_id" text,
	"company_id" text,
	"pipeline_id" text,
	"assigned_to" text,
	"expected_close" timestamp with time zone,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "invoice" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"number" text,
	"status" text,
	"company_id" text,
	"contact_id" text,
	"issue_date" timestamp with time zone,
	"due_date" timestamp with time zone,
	"lines" jsonb,
	"subtotal" numeric(15, 2),
	"tax" numeric(15, 2),
	"total" numeric(15, 2),
	"notes" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "milestone" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text,
	"project_id" text,
	"due_date" timestamp with time zone,
	"status" text,
	"description" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pipeline" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text,
	"stages" jsonb,
	"is_default" boolean
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "product" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"name" text,
	"sku" text,
	"price" numeric(15, 2),
	"cost" numeric(15, 2),
	"unit" text,
	"active" boolean,
	"description" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "project" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"name" text,
	"description" text,
	"status" text,
	"company_id" text,
	"budget" numeric(15, 2),
	"deadline" timestamp with time zone,
	"manager_id" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "quote" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"number" text,
	"status" text,
	"company_id" text,
	"contact_id" text,
	"deal_id" text,
	"issue_date" timestamp with time zone,
	"expiry_date" timestamp with time zone,
	"lines" jsonb,
	"subtotal" numeric(15, 2),
	"tax" numeric(15, 2),
	"total" numeric(15, 2),
	"notes" text
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "task" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"title" text,
	"description" text,
	"project_id" text,
	"status" text,
	"priority" text,
	"assignee_id" text,
	"due_date" timestamp with time zone,
	"estimated_hours" integer
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "time_entry" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"tenant_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"external_id" text,
	"source_system" text,
	"task_id" text,
	"project_id" text,
	"user_id" text,
	"hours" integer,
	"date" timestamp with time zone,
	"description" text,
	"billable" boolean
);
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "agent_keys" ADD CONSTRAINT "agent_keys_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "plugins" ADD CONSTRAINT "plugins_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "users" ADD CONSTRAINT "users_tenant_id_fkey" FOREIGN KEY ("tenant_id") REFERENCES "public"."tenants"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_keys_tenant_idx" ON "agent_keys" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_tenant_idx" ON "audit_log" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "audit_log_entity_idx" ON "audit_log" USING btree ("entity_name","record_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "migration_jobs_tenant_idx" ON "migration_jobs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "users_tenant_idx" ON "users" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "activity_tenant_idx" ON "activity" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "activity_external_idx" ON "activity" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "automation_tenant_idx" ON "automation" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "comment_tenant_idx" ON "comment" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "comment_external_idx" ON "comment" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "company_tenant_idx" ON "company" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "company_external_idx" ON "company" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "contact_tenant_idx" ON "contact" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "contact_external_idx" ON "contact" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "deal_tenant_idx" ON "deal" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "deal_external_idx" ON "deal" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invoice_tenant_idx" ON "invoice" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "invoice_external_idx" ON "invoice" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "milestone_tenant_idx" ON "milestone" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "pipeline_tenant_idx" ON "pipeline" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "product_tenant_idx" ON "product" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "product_external_idx" ON "product" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "project_tenant_idx" ON "project" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "project_external_idx" ON "project" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quote_tenant_idx" ON "quote" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "quote_external_idx" ON "quote" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "task_tenant_idx" ON "task" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "task_external_idx" ON "task" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "time_entry_tenant_idx" ON "time_entry" USING btree ("tenant_id");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "time_entry_external_idx" ON "time_entry" USING btree ("tenant_id","external_id","source_system") WHERE external_id IS NOT NULL;