import PDFDocument from "pdfkit";
import type { Hono, Context } from "hono";
import { entityService, isPermissionError } from "@meridian/core";
import type { ActorContext } from "@meridian/core";

interface LineItem {
  description?: string;
  quantity?: number;
  unitPrice?: number;
  amount?: number;
}

const currency = (n: unknown) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(n ?? 0));

function buildDocumentPdf(
  kind: "quote" | "invoice",
  record: Record<string, unknown>,
  partyName: string | null,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const title = kind === "quote" ? "QUOTE" : "INVOICE";
    const accent = "#2563eb";

    // Header
    doc.fontSize(22).fillColor(accent).font("Helvetica-Bold").text("Meridian", 50, 50);
    doc.fontSize(18).fillColor("#111").text(title, 0, 50, { align: "right" });
    doc
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#555")
      .text(String(record.number ?? ""), 0, 74, { align: "right" });

    doc.moveTo(50, 100).lineTo(545, 100).strokeColor("#e5e7eb").stroke();

    // Meta block
    let y = 116;
    doc.fontSize(9).fillColor("#888").text(kind === "quote" ? "PREPARED FOR" : "BILL TO", 50, y);
    doc.fontSize(11).fillColor("#111").font("Helvetica-Bold").text(partyName ?? "—", 50, y + 13);
    doc.font("Helvetica").fontSize(9).fillColor("#888");
    const dates: [string, unknown][] = [
      ["Issue date", record.issueDate],
      [kind === "quote" ? "Valid until" : "Due date", kind === "quote" ? record.expiryDate : record.dueDate],
      ["Status", record.status],
    ];
    let metaY = y;
    for (const [label, value] of dates) {
      doc.fillColor("#888").text(label, 350, metaY, { width: 90 });
      doc
        .fillColor("#111")
        .text(value ? String(value).slice(0, 10) : "—", 445, metaY, { width: 100, align: "right" });
      metaY += 14;
    }

    // Lines table
    y = 180;
    doc.rect(50, y, 495, 20).fill("#f3f4f6");
    doc.fillColor("#555").fontSize(9).font("Helvetica-Bold");
    doc.text("DESCRIPTION", 58, y + 6, { width: 250 });
    doc.text("QTY", 320, y + 6, { width: 50, align: "right" });
    doc.text("UNIT PRICE", 380, y + 6, { width: 75, align: "right" });
    doc.text("AMOUNT", 465, y + 6, { width: 72, align: "right" });
    y += 26;

    const lines: LineItem[] = Array.isArray(record.lines) ? (record.lines as LineItem[]) : [];
    doc.font("Helvetica").fontSize(10);
    if (lines.length === 0) {
      doc.fillColor("#888").text("No line items — totals imported from source system.", 58, y);
      y += 20;
    }
    for (const line of lines) {
      const qty = line.quantity ?? 1;
      const unit = line.unitPrice ?? 0;
      const amount = line.amount ?? qty * unit;
      doc.fillColor("#111").text(String(line.description ?? ""), 58, y, { width: 250 });
      const rowHeight = Math.max(doc.heightOfString(String(line.description ?? ""), { width: 250 }), 12);
      doc.text(String(qty), 320, y, { width: 50, align: "right" });
      doc.text(currency(unit), 380, y, { width: 75, align: "right" });
      doc.text(currency(amount), 465, y, { width: 72, align: "right" });
      y += rowHeight + 8;
      if (y > 720) {
        doc.addPage();
        y = 50;
      }
    }

    // Totals
    y += 8;
    doc.moveTo(350, y).lineTo(545, y).strokeColor("#e5e7eb").stroke();
    y += 10;
    const totals: [string, unknown, boolean][] = [
      ["Subtotal", record.subtotal, false],
      ["Tax", record.tax, false],
      ["Total", record.total, true],
    ];
    for (const [label, value, bold] of totals) {
      doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(bold ? 12 : 10);
      doc.fillColor(bold ? "#111" : "#555").text(label, 350, y, { width: 100 });
      doc.fillColor("#111").text(currency(value), 445, y, { width: 100, align: "right" });
      y += bold ? 20 : 16;
    }

    if (record.notes) {
      y += 12;
      doc.fontSize(9).fillColor("#888").font("Helvetica-Bold").text("NOTES", 50, y);
      doc.font("Helvetica").fontSize(10).fillColor("#333").text(String(record.notes), 50, y + 13, { width: 495 });
    }

    doc
      .fontSize(8)
      .fillColor("#aaa")
      .text(`Generated by Meridian · ${new Date().toISOString().slice(0, 10)}`, 50, 790, {
        width: 495,
        align: "center",
      });

    doc.end();
  });
}

export function registerPdfRoutes(app: Hono, getActor: (c: Context) => ActorContext | null): void {
  app.get("/api/documents/:entity/:id/pdf", async (c) => {
    const actor = getActor(c);
    if (!actor) return c.json({ error: "Unauthorized" }, 401);

    const entity = c.req.param("entity");
    if (entity !== "quote" && entity !== "invoice") {
      return c.json({ error: "PDF is available for quotes and invoices" }, 400);
    }

    try {
      const record = await entityService.read(entity, c.req.param("id")!, actor);

      let partyName: string | null = null;
      if (record.companyId) {
        partyName = await entityService
          .read("company", String(record.companyId), actor)
          .then((company) => String(company.name ?? ""))
          .catch(() => null);
      }
      if (!partyName && record.contactId) {
        partyName = await entityService
          .read("contact", String(record.contactId), actor)
          .then((contact) => [contact.firstName, contact.lastName].filter(Boolean).join(" "))
          .catch(() => null);
      }

      const pdf = await buildDocumentPdf(entity, record, partyName);
      c.header("Content-Type", "application/pdf");
      c.header(
        "Content-Disposition",
        `inline; filename="${entity}-${String(record.number ?? record.id).replace(/[^\w.-]/g, "_")}.pdf"`,
      );
      return c.body(new Uint8Array(pdf));
    } catch (err) {
      const message = (err as Error).message;
      const status = isPermissionError(err) ? 403 : message.includes("not found") ? 404 : 400;
      return c.json({ error: message }, status);
    }
  });
}
