import { randomBytes } from "node:crypto";
import { sql } from "drizzle-orm";
import { getDb } from "./client.js";
import { ensureEntityTables } from "./entity-store.js";
import { applyMigrations } from "./migrator.js";
import { assertSchemaMatchesRegistry } from "./schema-check.js";
import { hashPassword } from "../auth/password.js";

/**
 * Bring the database up to date, then verify it.
 *
 * Schema changes are versioned migrations under packages/core/drizzle/,
 * generated by `pnpm db:generate` from the entity registry and applied here
 * exactly once each. The follow-up drift check is a backstop: it catches an
 * entity that changed without a migration to match, and says so at startup
 * rather than letting the first request that touches the new field 500.
 *
 * Idempotent — safe to run on every boot. Callers must register entities
 * first; the API and worker do that at startup.
 */
export async function runMigrations(): Promise<void> {
  ensureEntityTables();
  await applyMigrations();
  await assertSchemaMatchesRegistry();
}

/**
 * The password the seeded admin gets.
 *
 * `demo1234` is fine on a laptop and indefensible on a public URL, and
 * AUTO_SEED is exactly the setting someone turns on for a first deploy. So in
 * production an unset DEMO_ADMIN_PASSWORD produces a random one, printed once
 * — an operator who has to read the deploy log to get in is a much better
 * failure mode than an instance anyone can sign into.
 */
export function demoAdminPassword(): string {
  const configured = process.env.DEMO_ADMIN_PASSWORD;
  if (configured) return configured;
  if (process.env.NODE_ENV !== "production") return "demo1234";

  const generated = randomBytes(18).toString("base64url");
  console.log(
    [
      "",
      "  ┌─────────────────────────────────────────────────────────────────┐",
      "  │  Seeded the demo admin with a generated password.               │",
      "  │  This is printed once. Save it, then change it in Settings.     │",
      "  └─────────────────────────────────────────────────────────────────┘",
      `  admin@demo.com  ${generated}`,
      "",
      "  Set DEMO_ADMIN_PASSWORD to choose it yourself next time.",
      "",
    ].join("\n"),
  );
  return generated;
}

/**
 * Seed the demo tenant, admin user, and example automation. Idempotent —
 * skips entirely if the demo tenant exists.
 */
export async function seedDemoTenant(): Promise<boolean> {
  const db = getDb();

  const existing = await db.execute(sql`SELECT id FROM tenants WHERE slug = 'demo' LIMIT 1`);
  if (existing.length > 0) return false;

  const tenantResult = await db.execute(sql`
    INSERT INTO tenants (name, slug) VALUES ('Demo Company', 'demo') RETURNING id
  `);
  const tenantId = (tenantResult[0] as { id: string }).id;

  const passwordHash = hashPassword(demoAdminPassword());
  await db.execute(sql`
    INSERT INTO users (tenant_id, email, name, role, password_hash)
    VALUES (${tenantId}, 'admin@demo.com', 'Demo Admin', 'admin', ${passwordHash})
  `);

  // Demo automation: winning a deal spins up a delivery project automatically
  await db.execute(sql`
    INSERT INTO automation (tenant_id, name, entity, event, conditions, actions, enabled)
    VALUES (
      ${tenantId},
      'Won deal → kickoff project',
      'deal',
      'updated',
      ${JSON.stringify([{ field: "stage", op: "eq", value: "won" }])}::jsonb,
      ${JSON.stringify([
        {
          type: "create_record",
          entity: "project",
          data: { name: "Delivery: {{title}}", status: "planning", description: "Auto-created from won deal {{recordId}}" },
        },
      ])}::jsonb,
      true
    )
  `);

  return true;
}
